name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  
    
    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v3.0.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.0.0
      with:
        name: dotnet_application          

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
      # Build's context is the set of files located in the specified PATH or URL
        context: .
      # Path to the Dockerfile
        file: ./Dockerfile
      # Push is a shorthand for --output=type=registry
        push: true
      # List of tags
        tags: gabrielandreato/dotnet_ci:${{github.ref_name}}
