name: Dotnet

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: ['6.0.0', '7.0.0'] 
        os: [ 'ubuntu-latest', 'ubuntu-18.04' ]
    steps:
    - uses: actions/checkout@v3  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: ['6.0.0', '7.0.0'] 
        os: [ 'ubuntu-latest', 'ubuntu-18.04' ]
    steps:
    - uses: actions/checkout@v3  
      with: 
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      

